version: '2'

services:

# redis database service
  redis:
    build:
      context: .
      dockerfile: redis.Dockerfile
    container_name: sudoku_db
    restart: always
    ports:
      - "6379:6379"

# application frontend sudoku service
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    depends_on:
      - redis
    container_name: frontend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - dev.env

# generator sudoku service
  generator:
    build:
      context: .
      dockerfile: generator.Dockerfile
    depends_on:
      - redis
    container_name: generator
    restart: always
    env_file:
      - dev.env
