package data

// User is a general structure of information about a user.
type User struct {
	// Username is the name of the user in user-defined case.
	Username string `json:"username"`
	// PasswordHash is generated by concatenating the password, salt and pepper and running it through the bcrypt hash
	// algorithm.
	PasswordHash string `json:"passwordHash"`
	// PasswordSalt is generated when a user registers.
	PasswordSalt string `json:"passwordSalt"`
	// SignupTimestamp is the date and time the user signed up.
	SignupTimestamp int64 `json:"signupTimestamp"`
}
